---
- id: root
  options:
    - id: news
      type: document_type_selection
    - id: guidance_and_regulation
      type: document_type_selection      

- id: news
  options:
    - id: news_story
      type: document_type
    - id: press_release
      type: document_type      

- id: guidance_and_regulation
  options:
    - id: guidance_publications
      type: document_type_selection      

- id: guidance_publications
  options:
    - id: guidance
      type: document_type    
    - id: statutory_guidance
      type: document_type      