---
- id: root
  options:
    - id: news
      type: document_type_selection

- id: news
  options:
    - id: news_story
      type: document_type
    - id: press_release
      type: document_type      